# Form implementation generated from reading ui file 'QDoubleSpinBox小数数字选择控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(110, 80, 151, 41))
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMinimum(-1.0)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", -0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.doubleSpinBox.setPrefix(_translate("Form", "第"))
        self.doubleSpinBox.setSuffix(_translate("Form", "秒"))
